version: "3"

services:
  feeds:
    image: emmanuerl/udagram-api-feeds
    # build:
    #   dockerfile: Dockerfile
    #   context: ./udagram-api-feeds
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=postgres
      - AWS_BUCKET=${AWS_BUCKET}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - JWT_SECRET=testing
      - PORT=80
    depends_on:
      - postgres

  users:
    image: emmanuerl/udagram-api-users
    # build:
    #   dockerfile: Dockerfile
    #   context: ./udagram-api-users
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=postgres
      - JWT_SECRET=testing
      - PORT=80
    depends_on:
      - postgres

  frontend:
    image: emmanuerl/udagram-frontend
    # build:
    #   dockerfile: Dockerfile
    #   context: ./udagram-frontend
  
  reverseproxy:
    # image: emmanuerl/udagram-reverseproxy
    build:
      dockerfile: Dockerfile
      context: ./udagram-reverseproxy
    ports:
      - 80:80
    depends_on:
      - feeds
      - users

  postgres:
    image: postgres:14-bullseye
    environment:
      - POSTGRES_PASSWORD=password